import AjoutMemo from "../screens/AjoutMemo/AjoutMemo";

export default Object.freeze({
  
    REGISTER_MALADE: 'Register_malade',
    WELCOME: 'Welcome',
    ROLE: 'Role',
    LOGIN_PROCHE:'Login_proche' ,
    LOGIN_MALADE:'Login_malade' ,
    LOGIN2: 'Login2',
    PROBLEM: 'Problem',
    CONNECTION: 'Connection',
    CODE:'Code',
    PILULIER2:'Pilulier2 ,',
    HOME_PROCHE: 'Home_proche',
    HOME_MALADE: 'Home_malade',
    REGISTER_PROCHE: 'Register_proche',
    URGENCE1: 'Urgence1' ,
    URGENCE2: 'Urgence2'  ,
    URGENCE3 : 'Urgence3' ,
    URGENCE4 : 'Urgence4' ,
    SCAN: 'Scan_code',
    PILULIER1:'Pilulier1' ,
    PILULIER3:'Pilulier3' ,
    PILULIER4:'Pilulier4' ,
    PILULIER2:'Pilulier2' ,
    PILULIER5:'Pilulier5' ,
    PILULIER6:'Pilulier6' ,
    PILULIER7:'Pilulier7' ,
    RAPPELS1: 'Rappels1' ,
    RAPPELS2:'Rappels2',
    RAPPELS3:'Rappels3',
    INFOADD:'infoAdd',
    TEST:'Test',
    NOTIFDONE:'NotificationsDone',
    NOTIFOUBLIE:'NotificationsOublie',
    NOTIFPENDING:'NotificationsPending',
    RAPPELSPILULIERDONE:'RappelsEtPilulierDone',
    RAPPELSPILULIEROUBLIE:'RappelsEtPilulierOublie',
    RAPPELSPILULIERPENDING:'RappelsEtPilulierPending',
    LOCALISER:'Localisation' ,
    GP1:'GP1',
    GP2:'GP2',
  
    GAMECONFIG:'ConfigJeux',
    
    JEU1:'Jeu1',
    JEU2:'Jeu2',
    JEU3:'Jeu3',
    JEU4:'Jeu4',
    JEU5:'Jeu5',
    MEMO:'Memo',
    LIST:'List' , 
    EDIT:'Edit' ,
    DIARY:'Diary' ,
    AJOUT_MEMO:'Ajout_memo'
}) 